package com.example.simpleledger;

import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.net.Uri;import android.os.Bundle;import android.os.Build;import android.os.Environment;import android.provider.Settings;import android.provider.MediaStore;import android.text.InputType;import android.view.*;import android.view.inputmethod.InputMethodManager;import android.widget.*;import org.json.*;import java.io.*;import java.math.*;import java.text.*;import java.util.*;

public class MainActivity extends Activity{
 static final String PREFS="simple_ledger_data",KEY_INITIAL="initial_balance_cents",KEY_ITEMS="transactions";static final int EXPORT=81,IMPORT=82;
 final ArrayList<Tx> items=new ArrayList<>();SharedPreferences prefs;long initial=0;LinearLayout content,homePage,recordsPage,list;TextView balance,expense,income,empty;Button navHome,navRecords,navFeatures;LinearLayout featuresPage;String themeKey="yellow";
 int ink,muted,yellow,bg,soft,line,deep;
 @Override public void onCreate(Bundle b){super.onCreate(b);requestWindowFeature(Window.FEATURE_NO_TITLE);prefs=getSharedPreferences(PREFS,MODE_PRIVATE);boolean hasInitial=prefs.contains(KEY_INITIAL);themeKey=prefs.getString("theme","yellow");applyPalette(themeKey);load();setContentView(build());refresh();if(!hasInitial){showInitial();}else if(initial!=0&&b==null){content.postDelayed(()->showTx(false,true),260);}}
 View build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(bg);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);root.addView(content,new LinearLayout.LayoutParams(-1,0,1));homePage=buildHome();recordsPage=buildRecords();featuresPage=buildFeatures();content.addView(homePage,new LinearLayout.LayoutParams(-1,-1));content.addView(recordsPage,new LinearLayout.LayoutParams(-1,-1));content.addView(featuresPage,new LinearLayout.LayoutParams(-1,-1));LinearLayout nav=new LinearLayout(this);nav.setPadding(dp(12),dp(7),dp(12),dp(9));nav.setBackground(round(Color.WHITE,0));navHome=navButton("⌂\n首页");navRecords=navButton("☷\n记录");navFeatures=navButton("✦\n功能");navHome.setOnClickListener(v->showPage(0));navRecords.setOnClickListener(v->showPage(1));navFeatures.setOnClickListener(v->showPage(2));nav.addView(navHome,new LinearLayout.LayoutParams(0,dp(62),1));nav.addView(navRecords,new LinearLayout.LayoutParams(0,dp(62),1));nav.addView(navFeatures,new LinearLayout.LayoutParams(0,dp(62),1));root.addView(nav);showPage(0);return root;}
 LinearLayout buildHome(){LinearLayout p=page();TextView title=t("小圆饼干",28,ink,true);title.setGravity(Gravity.CENTER);p.addView(title,new LinearLayout.LayoutParams(-1,-2));TextView sub=t(dateWithLunar(),13,muted,false);sub.setGravity(Gravity.CENTER);lpTop(p,sub,6);addFlexSpace(p,2);balance=metricCard(p,"总存款",yellow,39);addFlexSpace(p,2);LinearLayout pair=new LinearLayout(this);pair.setOrientation(LinearLayout.HORIZONTAL);p.addView(pair,new LinearLayout.LayoutParams(-1,dp(190)));expense=squareMetric(pair,"−","本月支出",soft);income=squareMetric(pair,"＋","本月收入",Color.rgb((Color.red(yellow)+255)/2,(Color.green(yellow)+255)/2,(Color.blue(yellow)+255)/2));addFlexSpace(p,2);LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);TextView out=action("记支出",soft),in=action("记收入",yellow);out.setOnClickListener(v->showTx(false));in.setOnClickListener(v->showTx(true));row.addView(out,new LinearLayout.LayoutParams(0,dp(58),1));LinearLayout.LayoutParams ilp=new LinearLayout.LayoutParams(0,dp(58),1);ilp.leftMargin=dp(12);row.addView(in,ilp);p.addView(row,new LinearLayout.LayoutParams(-1,dp(58)));addFlexSpace(p,3);return p;}
 TextView squareMetric(LinearLayout row,String symbol,String label,int color){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setGravity(Gravity.CENTER);c.setPadding(dp(14),dp(14),dp(14),dp(14));c.setBackground(round(Color.WHITE,24));TextView sym=t(symbol,30,ink,true);sym.setGravity(Gravity.CENTER);sym.setBackground(round(color,17));c.addView(sym,new LinearLayout.LayoutParams(dp(52),dp(52)));TextView lab=t(label,19,muted,true);lab.setGravity(Gravity.CENTER);LinearLayout.LayoutParams llp=new LinearLayout.LayoutParams(-1,-2);llp.topMargin=dp(12);c.addView(lab,llp);TextView v=t("¥0.00",29,ink,true);v.setGravity(Gravity.CENTER);LinearLayout.LayoutParams vlp=new LinearLayout.LayoutParams(-1,-2);vlp.topMargin=dp(7);c.addView(v,vlp);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,-1,1);row.addView(c,lp);if(row.getChildCount()==1){LinearLayout.LayoutParams nlp=(LinearLayout.LayoutParams)c.getLayoutParams();nlp.rightMargin=dp(7);c.setLayoutParams(nlp);}else{LinearLayout.LayoutParams nlp=(LinearLayout.LayoutParams)c.getLayoutParams();nlp.leftMargin=dp(7);c.setLayoutParams(nlp);}return v;}
 LinearLayout buildRecords(){LinearLayout p=page();TextView title=t("收支记录",27,ink,true);title.setGravity(Gravity.CENTER_VERTICAL);p.addView(title,new LinearLayout.LayoutParams(-1,-2));ScrollView sv=new ScrollView(this);sv.setFillViewport(true);sv.setClipToPadding(false);sv.setPadding(0,0,0,dp(18));list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);sv.addView(list);LinearLayout.LayoutParams slp=new LinearLayout.LayoutParams(-1,0,1);slp.topMargin=dp(12);p.addView(sv,slp);empty=t("还没有记录\n从首页记下第一笔吧",14,muted,false);empty.setGravity(Gravity.CENTER);return p;}
 LinearLayout buildFeatures(){LinearLayout p=page();p.addView(t("功能",27,ink,true));TextView sub=t("设置、皮肤与数据备份",13,muted,false);lpTop(p,sub,4);TextView skinTitle=t("马卡龙皮肤",13,muted,true);lpTop(p,skinTitle,24);LinearLayout skins=new LinearLayout(this);skins.setOrientation(LinearLayout.HORIZONTAL);p.addView(skins,top(10));String[] keys={"yellow","pink","mint","blue","purple"};String[] names={"奶油黄","蜜桃粉","薄荷绿","晴空蓝","香芋紫"};int[] cs={Color.rgb(255,214,107),Color.rgb(246,185,200),Color.rgb(174,227,197),Color.rgb(184,217,247),Color.rgb(213,189,241)};for(int i=0;i<keys.length;i++){final String k=keys[i];LinearLayout one=new LinearLayout(this);one.setGravity(Gravity.CENTER);one.setOrientation(LinearLayout.VERTICAL);TextView dot=t("",1,ink,false);dot.setBackground(round(cs[i],30));one.addView(dot,new LinearLayout.LayoutParams(dp(48),dp(48)));TextView nm=t(names[i],10,muted,false);lpTop(one,nm,5);one.setOnClickListener(v->{prefs.edit().putString("theme",k).apply();recreate();});skins.addView(one,new LinearLayout.LayoutParams(0,dp(82),1));}TextView account=t("账户设置",13,muted,true);lpTop(p,account,18);p.addView(tool("调整总存款","修改当前账户的初始存款金额",v->showInitial()),top(9));TextView dataTitle=t("数据管理",13,muted,true);lpTop(p,dataTitle,20);p.addView(tool("导出备份","保存为 JSON 文件，可用于换手机或恢复数据",v->exportData()),top(9));p.addView(tool("导入恢复","选择此前导出的 JSON 备份文件",v->importData()),top(9));p.addView(tool("清空全部数据","删除初始存款及所有收支记录",v->clearAll()),top(9));return p;}
 LinearLayout page(){LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setPadding(dp(19),dp(52),dp(19),dp(18));return p;}
 TextView metricCard(LinearLayout p,String label,int color,int size){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setGravity(Gravity.CENTER);c.setPadding(dp(22),dp(24),dp(22),dp(24));c.setBackground(round(color,27));p.addView(c,new LinearLayout.LayoutParams(-1,dp(126)));TextView lab=t(label,15,ink,true);lab.setGravity(Gravity.CENTER);c.addView(lab,new LinearLayout.LayoutParams(-1,-2));TextView v=t("¥0.00",size,ink,true);v.setGravity(Gravity.CENTER);LinearLayout.LayoutParams vlp=new LinearLayout.LayoutParams(-1,-2);vlp.topMargin=dp(7);c.addView(v,vlp);return v;}
 void addFlexSpace(LinearLayout p,int weight){Space sp=new Space(this);p.addView(sp,new LinearLayout.LayoutParams(1,0,weight));}
 String dateWithLunar(){Date now=new Date();String solar=new SimpleDateFormat("M月d日",Locale.CHINA).format(now);if(Build.VERSION.SDK_INT<24)return solar;try{android.icu.util.ChineseCalendar c=new android.icu.util.ChineseCalendar();c.setTime(now);int month=c.get(android.icu.util.Calendar.MONTH)+1;int day=c.get(android.icu.util.Calendar.DAY_OF_MONTH);boolean leap=c.get(android.icu.util.ChineseCalendar.IS_LEAP_MONTH)==1;String[] ms={"正月","二月","三月","四月","五月","六月","七月","八月","九月","十月","冬月","腊月"};String[] ds={"初一","初二","初三","初四","初五","初六","初七","初八","初九","初十","十一","十二","十三","十四","十五","十六","十七","十八","十九","二十","廿一","廿二","廿三","廿四","廿五","廿六","廿七","廿八","廿九","三十"};String lunar=(leap?"闰":"")+(month>=1&&month<=12?ms[month-1]:month+"月")+(day>=1&&day<=30?ds[day-1]:day+"日");return solar+" · 农历"+lunar;}catch(Exception e){return solar;}}
 void showPage(int which){homePage.setVisibility(which==0?View.VISIBLE:View.GONE);recordsPage.setVisibility(which==1?View.VISIBLE:View.GONE);featuresPage.setVisibility(which==2?View.VISIBLE:View.GONE);navHome.setTextColor(which==0?deep:muted);navRecords.setTextColor(which==1?deep:muted);navFeatures.setTextColor(which==2?deep:muted);}
 void applyPalette(String k){themeKey=k;if(k.equals("pink")){bg=Color.rgb(255,241,244);yellow=Color.rgb(246,185,200);soft=Color.rgb(251,217,225);deep=Color.rgb(185,91,120);ink=Color.rgb(86,49,60);muted=Color.rgb(155,116,128);line=Color.rgb(240,208,217);}else if(k.equals("mint")){bg=Color.rgb(239,251,244);yellow=Color.rgb(174,227,197);soft=Color.rgb(217,243,228);deep=Color.rgb(78,155,114);ink=Color.rgb(40,72,58);muted=Color.rgb(110,145,130);line=Color.rgb(204,232,216);}else if(k.equals("blue")){bg=Color.rgb(240,247,255);yellow=Color.rgb(184,217,247);soft=Color.rgb(220,236,255);deep=Color.rgb(93,143,189);ink=Color.rgb(45,67,87);muted=Color.rgb(113,136,155);line=Color.rgb(208,226,242);}else if(k.equals("purple")){bg=Color.rgb(247,241,255);yellow=Color.rgb(213,189,241);soft=Color.rgb(234,220,248);deep=Color.rgb(131,97,173);ink=Color.rgb(68,52,82);muted=Color.rgb(136,118,150);line=Color.rgb(223,209,236);}else{bg=Color.rgb(255,248,221);yellow=Color.rgb(255,214,107);soft=Color.rgb(255,240,181);deep=Color.rgb(189,125,21);ink=Color.rgb(77,57,28);muted=Color.rgb(154,128,89);line=Color.rgb(242,223,173);}getWindow().setStatusBarColor(bg);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);}
 void showInitial(){EditText a=styledInput("当前总存款",true);a.setText(plain(initial));a.setSelectAllOnFocus(true);showCuteDialog("设置总存款",a,null,()->{Long c=parse(a.getText().toString());if(c==null){a.setError("请输入正确金额");return false;}initial=c;save();refresh();return true;});}
 void showTx(boolean inc){showTx(inc,false);}void showTx(boolean inc,boolean autoFocus){EditText a=styledInput("多少钱",true),n=styledInput(inc?"来源":"用途",false);showCuteDialog(inc?"记录收入":"记录支出",a,n,()->{Long c=parse(a.getText().toString());if(c==null||c<=0){a.setError("请输入大于0的金额");return false;}String note=n.getText().toString().trim();if(note.isEmpty())note=inc?"收入":"支出";items.add(0,new Tx(System.currentTimeMillis(),inc,c,note));save();refresh();return true;},autoFocus);}
 interface Saver{boolean go();}
 void showCuteDialog(String title,EditText first,EditText second,Saver saver){showCuteDialog(title,first,second,saver,false);}void showCuteDialog(String title,EditText first,EditText second,Saver saver,boolean autoFocus){
  final Dialog d=new Dialog(this);d.requestWindowFeature(Window.FEATURE_NO_TITLE);
  ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setClipToPadding(false);scroll.setPadding(0,dp(8),0,dp(20));
  LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(22),dp(22),dp(22),dp(38));
  GradientDrawable cardBg=round(bg,28);cardBg.setStroke(dp(2),line);card.setBackground(cardBg);scroll.addView(card,new ScrollView.LayoutParams(-1,-2));
  TextView ttl=t(title,23,ink,true);ttl.setGravity(Gravity.CENTER);card.addView(ttl,new LinearLayout.LayoutParams(-1,-2));
  LinearLayout.LayoutParams fp=new LinearLayout.LayoutParams(-1,dp(58));fp.topMargin=dp(20);card.addView(first,fp);
  if(second!=null){LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,dp(58));sp.topMargin=dp(12);card.addView(second,sp);}
  LinearLayout buttons=new LinearLayout(this);buttons.setOrientation(LinearLayout.HORIZONTAL);buttons.setGravity(Gravity.CENTER);
  TextView cancel=dialogButton("取消",Color.WHITE,muted);TextView saveBtn=dialogButton("保存",yellow,ink);
  LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(0,dp(58),1);buttons.addView(cancel,cp);
  LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(0,dp(58),1);bp.leftMargin=dp(12);buttons.addView(saveBtn,bp);
  LinearLayout.LayoutParams buttonsLp=new LinearLayout.LayoutParams(-1,dp(58));buttonsLp.topMargin=dp(24);buttonsLp.bottomMargin=dp(24);card.addView(buttons,buttonsLp);
  d.setContentView(scroll);cancel.setOnClickListener(v->d.dismiss());saveBtn.setOnClickListener(v->{if(saver.go())d.dismiss();});d.show();
  Window w=d.getWindow();if(w!=null){w.setBackgroundDrawableResource(android.R.color.transparent);w.addFlags(WindowManager.LayoutParams.FLAG_DIM_BEHIND);w.setGravity(Gravity.CENTER);WindowManager.LayoutParams lp=w.getAttributes();lp.width=(int)(getResources().getDisplayMetrics().widthPixels*0.90f);lp.height=WindowManager.LayoutParams.WRAP_CONTENT;lp.dimAmount=.35f;w.setAttributes(lp);w.setSoftInputMode((autoFocus?WindowManager.LayoutParams.SOFT_INPUT_STATE_ALWAYS_VISIBLE:WindowManager.LayoutParams.SOFT_INPUT_STATE_UNSPECIFIED)|WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);}
  if(autoFocus){first.requestFocus();first.setSelection(first.getText().length());first.postDelayed(()->{InputMethodManager imm=(InputMethodManager)getSystemService(INPUT_METHOD_SERVICE);if(imm!=null)imm.showSoftInput(first,InputMethodManager.SHOW_IMPLICIT);},180);}
 }
 EditText styledInput(String hint,boolean money){EditText e=new EditText(this);e.setHint(hint);e.setHintTextColor(muted);e.setTextColor(ink);e.setTextSize(money?21:17);e.setSingleLine(true);e.setPadding(dp(17),0,dp(17),0);GradientDrawable g=round(Color.WHITE,18);g.setStroke(dp(2),line);e.setBackground(g);if(money)e.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);return e;}
 TextView dialogButton(String text,int color,int textColor){TextView b=t(text,17,textColor,true);b.setGravity(Gravity.CENTER);b.setIncludeFontPadding(true);b.setPadding(dp(10),dp(6),dp(10),dp(6));GradientDrawable g=round(color,20);g.setStroke(dp(1),line);b.setBackground(g);return b;}
 void refresh(){long b=initial,mi=0,me=0;String ym=new SimpleDateFormat("yyyy-MM",Locale.getDefault()).format(new Date());SimpleDateFormat f=new SimpleDateFormat("yyyy-MM",Locale.getDefault());for(Tx x:items){b+=x.inc?x.cents:-x.cents;if(f.format(new Date(x.time)).equals(ym)){if(x.inc)mi+=x.cents;else me+=x.cents;}}balance.setText(money(b));income.setText(money(mi));expense.setText(money(me));if(list==null)return;list.removeAllViews();if(items.isEmpty()){list.addView(empty,new LinearLayout.LayoutParams(-1,dp(150)));return;}String lastMonth="";SimpleDateFormat keyFmt=new SimpleDateFormat("yyyy-MM",Locale.getDefault());SimpleDateFormat monthFmt=new SimpleDateFormat("yyyy年M月",Locale.CHINA);SimpleDateFormat timeFmt=new SimpleDateFormat("M月d日 HH:mm",Locale.CHINA);for(Tx x:items){String monthKey=keyFmt.format(new Date(x.time));if(!monthKey.equals(lastMonth)){lastMonth=monthKey;long monthIn=0,monthOut=0;for(Tx q:items){if(keyFmt.format(new Date(q.time)).equals(monthKey)){if(q.inc)monthIn+=q.cents;else monthOut+=q.cents;}}LinearLayout monthHead=new LinearLayout(this);monthHead.setOrientation(LinearLayout.VERTICAL);monthHead.setPadding(dp(4),dp(14),dp(4),dp(7));TextView mt=t(monthFmt.format(new Date(x.time)),18,ink,true);monthHead.addView(mt);TextView ms=t("收入 "+money(monthIn)+"  ·  支出 "+money(monthOut),12,muted,false);lpTop(monthHead,ms,4);list.addView(monthHead,new LinearLayout.LayoutParams(-1,-2));}LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(15),dp(14),dp(15),dp(14));row.setBackground(round(Color.WHITE,19));LinearLayout left=new LinearLayout(this);left.setOrientation(LinearLayout.VERTICAL);left.addView(t(x.note,16,ink,true));TextView tm=t(timeFmt.format(new Date(x.time))+" · 点击删除",12,muted,false);lpTop(left,tm,4);row.addView(left,new LinearLayout.LayoutParams(0,-2,1));row.addView(t((x.inc?"+":"−")+money(x.cents),17,ink,true));row.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("删除这条记录？").setMessage(x.note+"  "+(x.inc?"+":"−")+money(x.cents)).setNegativeButton("取消",null).setPositiveButton("删除",(d,w)->{items.remove(x);save();refresh();}).show());list.addView(row,top(8));}}
 void exportData(){String name="小圆饼干备份_"+new SimpleDateFormat("yyyy-MM-dd_HHmm",Locale.getDefault()).format(new Date())+".json";if(Build.VERSION.SDK_INT>=29){try{ContentValues values=new ContentValues();values.put(MediaStore.Downloads.DISPLAY_NAME,name);values.put(MediaStore.Downloads.MIME_TYPE,"application/json");values.put(MediaStore.Downloads.RELATIVE_PATH,Environment.DIRECTORY_DOWNLOADS+"/小圆饼干");Uri uri=getContentResolver().insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI,values);if(uri==null)throw new IOException("无法创建文件");OutputStream o=getContentResolver().openOutputStream(uri);if(o==null)throw new IOException("无法写入文件");o.write(backup().toString(2).getBytes("UTF-8"));o.close();new AlertDialog.Builder(this).setTitle("导出成功").setMessage("备份文件已保存到：\n下载/小圆饼干/"+name).setPositiveButton("知道了",null).show();return;}catch(Exception e){toast("自动保存失败，请手动选择位置");}}Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/json");i.putExtra(Intent.EXTRA_TITLE,name);startActivityForResult(i,EXPORT);}void importData(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("application/json");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,IMPORT);}
 @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(c!=RESULT_OK||d==null||d.getData()==null)return;try{if(r==EXPORT){OutputStream o=getContentResolver().openOutputStream(d.getData());o.write(backup().toString(2).getBytes("UTF-8"));o.close();toast("备份已导出");}else if(r==IMPORT){BufferedReader br=new BufferedReader(new InputStreamReader(getContentResolver().openInputStream(d.getData()),"UTF-8"));StringBuilder s=new StringBuilder();String line;while((line=br.readLine())!=null)s.append(line);br.close();JSONObject x=new JSONObject(s.toString());long ni=x.getLong("initial");String nt=x.optString("theme",themeKey);JSONArray a=x.getJSONArray("items");ArrayList<Tx> parsed=new ArrayList<>();for(int j=0;j<a.length();j++){JSONObject q=a.getJSONObject(j);parsed.add(new Tx(q.getLong("time"),q.getBoolean("income"),q.getLong("cents"),q.getString("note")));}new AlertDialog.Builder(this).setTitle("恢复备份？").setMessage("导入会覆盖当前数据，共 "+parsed.size()+" 条记录。").setNegativeButton("取消",null).setPositiveButton("恢复",(z,w)->{initial=ni;items.clear();items.addAll(parsed);prefs.edit().putString("theme",nt).apply();save();toast("数据恢复成功");recreate();}).show();}}catch(Exception e){toast("文件无效或读取失败");}}
 JSONObject backup()throws JSONException{JSONObject root=new JSONObject();root.put("version",3);root.put("theme",themeKey);root.put("initial",initial);JSONArray a=new JSONArray();for(Tx x:items){JSONObject q=new JSONObject();q.put("time",x.time);q.put("income",x.inc);q.put("cents",x.cents);q.put("note",x.note);a.put(q);}root.put("items",a);return root;}
 void clearAll(){new AlertDialog.Builder(this).setTitle("清空全部数据？").setMessage("该操作无法撤销，建议先导出备份。 ").setNegativeButton("取消",null).setPositiveButton("清空",(d,w)->{initial=0;items.clear();save();refresh();toast("已清空");}).show();}
 void load(){initial=prefs.getLong(KEY_INITIAL,0);try{JSONArray a=new JSONArray(prefs.getString(KEY_ITEMS,"[]"));for(int i=0;i<a.length();i++){JSONObject q=a.getJSONObject(i);items.add(new Tx(q.getLong("time"),q.getBoolean("income"),q.getLong("cents"),q.getString("note")));}}catch(Exception ignored){}}
 void save(){try{prefs.edit().putLong(KEY_INITIAL,initial).putString(KEY_ITEMS,backup().getJSONArray("items").toString()).apply();}catch(Exception ignored){}}
Long parse(String s){try{return new BigDecimal(s.trim()).setScale(2,RoundingMode.HALF_UP).movePointRight(2).longValueExact();}catch(Exception e){return null;}}String money(long c){return "¥"+BigDecimal.valueOf(c,2).setScale(2).toPlainString();}String plain(long c){return BigDecimal.valueOf(c,2).setScale(2).toPlainString();}
 Button navButton(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(14);b.setBackgroundColor(Color.TRANSPARENT);return b;}TextView action(String s,int color){TextView b=t(s,16,ink,true);b.setGravity(Gravity.CENTER);b.setIncludeFontPadding(false);b.setPadding(dp(8),dp(3),dp(8),dp(5));b.setBackground(round(color,18));return b;}LinearLayout tool(String a,String b,View.OnClickListener l){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(dp(17),dp(15),dp(17),dp(15));x.setBackground(round(Color.WHITE,19));x.addView(t(a,15,ink,true));TextView s=t(b,12,muted,false);lpTop(x,s,4);x.setOnClickListener(l);return x;}TextView t(String s,int z,int c,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);if(bold)v.setTypeface(null,1);return v;}GradientDrawable round(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}LinearLayout.LayoutParams top(int m){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=dp(m);return p;}void lpTop(LinearLayout p,View v,int m){p.addView(v,top(m));}int dp(int x){return(int)(x*getResources().getDisplayMetrics().density+.5f);}void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}static class Tx{long time,cents;boolean inc;String note;Tx(long t,boolean i,long c,String n){time=t;inc=i;cents=c;note=n;}}
}
